app/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout
from django.utils.translation import ugettext_lazy as _

from .views import ArticleDetailView
from .views import ArticleDownVoteView
from .views import ArticleUpVoteView
from .views import CategoryDetailView
from .views import HomeView
from .views import LoginView
from .views import SearchResultsListView
from .views import ArticleDetailFeedbackView


admin.site.site_title = _('Knowledge Base')
admin.site.site_header = _('Knowledge Base')


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^markdownx/', include('markdownx.urls')),

    url(r'^robots\.txt', include('robots.urls')),

    url(
        _(r'^search/$'),
        SearchResultsListView.as_view(),
        name='search_results_list'
    ),

    url(
        _(r'^login/$'),
        LoginView.as_view(),
        name='login'
    ),

    url(
        _(r'^logout/$'),
        logout,
        {'next_page': '/'},
        name='logout'
    ),

    url(r'^$', HomeView.as_view(), name='home'),

    url(
        r'^(?P<slug>[\w\-]+)/$',
        CategoryDetailView.as_view(),
        name='category_detail'
    ),

    url(
        r'^(?P<category_slug>[\w\-]+)/(?P<slug>[\w\-]+)/$',
        ArticleDetailView.as_view(),
        name='article_detail'
    ),

    url(
        r'^(?P<category_slug>[\w\-]+)/(?P<slug>[\w\-]+)/send_feedback/$',
        ArticleDetailFeedbackView.as_view(),
        name='article_feedback_form'
    ),

    url(
        r'^(?P<category_slug>[\w\-]+)/(?P<slug>[\w\-]+)/upvote/$',
        ArticleUpVoteView.as_view(),
        name='article_upvote'
    ),

    url(
        r'^(?P<category_slug>[\w\-]+)/(?P<slug>[\w\-]+)/downvote/$',
        ArticleDownVoteView.as_view(),
        name='article_downvote'
    ),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.module_loading import import_string


class Category(models.Model):
    name = models.CharField(
        max_length=40,
        unique=True,
    )

    slug = models.SlugField(
        unique=True,
    )

    def active_articles_list(self):
        return self.article_set.filter(
            is_active=True,
        )

    def get_absolute_url(self):
        return reverse(
            'category_detail',
            args=[self.slug]
        )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class ActiveArticlesManager(models.Manager):
    def get_queryset(self):
        return super(ActiveArticlesManager, self).get_queryset().filter(
            is_active=True,
        )


class PublicArticlesManager(ActiveArticlesManager):
    def get_queryset(self):
        return super(PublicArticlesManager, self).get_queryset().filter(
            is_private=False,
        )


class Article(models.Model):
    category = models.ForeignKey(Category)

    name = models.CharField(
        max_length=50,
        unique=True,
    )

    slug = models.SlugField()

    is_active = models.BooleanField(
        default=True,
    )

    is_private = models.BooleanField()

    content = models.TextField()

    upvotes = models.PositiveIntegerField(
        default=0,
        editable=False,
    )

    downvotes = models.PositiveIntegerField(
        default=0,
        editable=False,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    objects = models.Manager()

    actives = ActiveArticlesManager()

    publics = PublicArticlesManager()

    @property
    def content_markdown(self):
        markdownify = import_string(settings.MARKDOWNX_MARKDOWNIFY_FUNCTION)
        return markdownify(self.content)

    def get_absolute_url(self):
        return reverse(
            'article_detail',
            args=[self.category.slug, self.slug]
        )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        unique_together = ('category', 'slug')

app/templates/app/article_detail.html
{% extends 'layout/base.html' %}
{% load i18n %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<section class="article-detail">
    <div class="breadcrumbs">
        <div class="container">
            <a href="{% url 'home' %}">{% trans "Home" %}</a> > <a href="{{ object.category.get_absolute_url }}">{{ object.category.name }}</a> > {{ object.name }}
        </div>
    </div>
    <div class="info-container">
        <div class="container">
            <h1>{{ object.name }}</h1>
            <div class="last-update">{% trans "Last updated" %} {{ object.updated_at }}</div>
            {% if object.is_private %}
            <blockquote>{% trans "This is private article. Only authenticated users can see it." %}</blockquote>
            {% endif %}
            <article>
                {{ object.content_markdown|safe }}
            </article>
            {% if not already_voted %}
            <div class="vote-buttons">
                <h6>{% trans "Was this article helpful?" %}</h6>
                <ul>
                    <li class="vote-up">
                        <button class="btn green">{% trans "Yes" %} ({{ object.upvotes }})</button>
                    </li>
                    <li class="vote-down">
                        <button class="btn red">{% trans "No" %} ({{ object.downvotes }})</button>
                    </li>
                </ul>
                <div class="thank-you hide">
                    <h3>{% trans "Thank you for your feedback!" %}</h3>
                </div>

                <div class="feedback {% if not display_form %}hide{% endif %}">
                    <h4>{% trans "Sorry about that. Why wasn’t it helpful?" %}</h4>
                    <form method="POST" action="{% url 'article_feedback_form' object.category.slug object.slug %}">
                        {% csrf_token %}
                        {{ feedback_form.as_p }}
                        <input type="submit" value="{% trans "Send" %}" class="btn green">
                    </form>
                </div>

            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
$(document).ready(function () {

    // Upvote
    $('div.vote-buttons li.vote-up button').click(function () {
        if ($(this).hasClass('disabled')) return;

        $.get("{% url 'article_upvote' object.category.slug object.slug %}", function(response) {
            $('.vote-buttons .thank-you').removeClass('hide');
            $('.vote-buttons .feedback').remove();
            $('.vote-buttons ul').remove();
            $('.vote-buttons h6').remove();
        });

        // Track event in Analytics.
        ga('send', 'event', 'click', 'upvote', window.location.href);
        return false;
    });

    // Downvote
    $('div.vote-buttons li.vote-down button').click(function () {
        if ($(this).hasClass('disabled')) return;

        $.get("{% url 'article_downvote' object.category.slug object.slug %}", function(response) {
            $('.vote-buttons ul button').addClass('disabled');

            // Show feedback form.
            $('.vote-buttons .feedback').removeClass('hide');
        });

        // Track event in Analytics.
        ga('send', 'event', 'click', 'downvote', window.location.href);
        return false;
    });

});
</script>
{% endblock %}

app/templates/app/article_search.html
{% extends 'layout/base.html' %}
{% load i18n %}

{% block title %}{% trans "Search results" %}{% endblock %}

{% block content %}
<section class="article-search">
    <div class="breadcrumbs">
        <div class="container">
            <a href="{% url 'home' %}">{% trans "Home" %}</a> > {% trans "Search results" %}
        </div>
    </div>

    <div class="search-box-container">
        <h1>{% trans "How can we help you today?" %}</h1>
        {% include '_search_box.html' %}
    </div>

    <div class="container info-container">
        {% for article in object_list %}
            <div class="article-search-container">
                <h2>{{ article.name }}</h2>
                <p>{{ article.content_markdown|truncatewords_html:20|safe }}</p>
                <a href="{% url 'article_detail' article.category.slug article.slug %}">Leer más...</a>
            </div>
        {% empty %}
            <p>No se encuentran resultados acordes con tu búsqueda, puedes abrir un nuevo tiquete con tu pregunta.</p>
        {% endfor %}
    </div>
</section>
{% endblock %}

app/templates/app/category_detail.html
{% extends 'layout/base.html' %}
{% load i18n %}

{% block title %}{% trans "Category" %} {{ object.name }}{% endblock %}

{% block content %}
<section class="category-detail">
    <div class="breadcrumbs"> 
        <div class="container">
            <a href="{% url 'home' %}">{% trans "Home" %}</a> > {{ object.name }}
        </div>
    </div>
    <div class="info-container">
        <div class="container-xs">
            <h1>{{ object.name }}</h1>
            <ul>
            {% for article in article_list %}
                <li>
                    <a href="{{ article.get_absolute_url }}">{{ article.name }}</a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</section>
{% endblock %}

app/templates/app/search_results_list.html
{% extends 'layout/base.html' %}

{% block content %}
    {% include '_search_box.html' %}

    {% for article in object_list %}
        <h1>{{ article.name }}</h1>
        <p>
            {{ article.content|truncatewords_html:20 }}
        </p>
        <a href="{% url 'article_detail' article.category.slug article.slug %}">Leer más...</a>

    {% empty %}
    <p>No se encuentran resultados acordes con tu búsqueda, puedes abrir un nuevo tiquete con tu pregunta.</p>
    {% endfor %}
{% endblock %}