app/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout
from django.utils.translation import ugettext_lazy as _

from .views import ArticleDetailView
from .views import ArticleDownVoteView
from .views import ArticleUpVoteView
from .views import CategoryDetailView
from .views import HomeView
from .views import LoginView
from .views import SearchResultsListView
from .views import ArticleDetailFeedbackView


admin.site.site_title = _('Knowledge Base')
admin.site.site_header = _('Knowledge Base')


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^markdownx/', include('markdownx.urls')),

    url(r'^robots\.txt', include('robots.urls')),

    url(
        _(r'^search/$'),
        SearchResultsListView.as_view(),
        name='search_results_list'
    ),

    url(
        _(r'^login/$'),
        LoginView.as_view(),
        name='login'
    ),

    url(
        _(r'^logout/$'),
        logout,
        {'next_page': '/'},
        name='logout'
    ),

    url(r'^$', HomeView.as_view(), name='home'),

    url(
        r'^(?P<slug>[\w\-]+)/$',
        CategoryDetailView.as_view(),
        name='category_detail'
    ),

    url(
        r'^(?P<category_slug>[\w\-]+)/(?P<slug>[\w\-]+)/$',
        ArticleDetailView.as_view(),
        name='article_detail'
    ),

    url(
        r'^(?P<category_slug>[\w\-]+)/(?P<slug>[\w\-]+)/send_feedback/$',
        ArticleDetailFeedbackView.as_view(),
        name='article_feedback_form'
    ),

    url(
        r'^(?P<category_slug>[\w\-]+)/(?P<slug>[\w\-]+)/upvote/$',
        ArticleUpVoteView.as_view(),
        name='article_upvote'
    ),

    url(
        r'^(?P<category_slug>[\w\-]+)/(?P<slug>[\w\-]+)/downvote/$',
        ArticleDownVoteView.as_view(),
        name='article_downvote'
    ),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.module_loading import import_string


class Category(models.Model):
    name = models.CharField(
        max_length=40,
        unique=True,
    )

    slug = models.SlugField(
        unique=True,
    )

    def active_articles_list(self):
        return self.article_set.filter(
            is_active=True,
        )

    def get_absolute_url(self):
        return reverse(
            'category_detail',
            args=[self.slug]
        )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class ActiveArticlesManager(models.Manager):
    def get_queryset(self):
        return super(ActiveArticlesManager, self).get_queryset().filter(
            is_active=True,
        )


class PublicArticlesManager(ActiveArticlesManager):
    def get_queryset(self):
        return super(PublicArticlesManager, self).get_queryset().filter(
            is_private=False,
        )


class Article(models.Model):
    category = models.ForeignKey(Category)

    name = models.CharField(
        max_length=50,
        unique=True,
    )

    slug = models.SlugField()

    is_active = models.BooleanField(
        default=True,
    )

    is_private = models.BooleanField()

    content = models.TextField()

    upvotes = models.PositiveIntegerField(
        default=0,
        editable=False,
    )

    downvotes = models.PositiveIntegerField(
        default=0,
        editable=False,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    objects = models.Manager()

    actives = ActiveArticlesManager()

    publics = PublicArticlesManager()

    @property
    def content_markdown(self):
        markdownify = import_string(settings.MARKDOWNX_MARKDOWNIFY_FUNCTION)
        return markdownify(self.content)

    def get_absolute_url(self):
        return reverse(
            'article_detail',
            args=[self.category.slug, self.slug]
        )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        unique_together = ('category', 'slug')

app/templates/429.html
{% extends 'layout/base.html' %}
{% load i18n %}

{% block title %}{% trans "Access Denied" %}{% endblock %}

{% block content %}
<section class="error">
    <h1>{% trans "Your access was denied" %}</h1>
    <p>{% trans "Please contact your administrator" %}.</p>
    <img src="https://s3.amazonaws.com/uploads.hipchat.com/50553/1957220/8TqPuJ7gWdK6viM/error-img-2.jpeg" />
    <p><a href="/" class="btn blue">{% trans "Go to the home page" %}</a></p>
</section>
{% endblock %}

app/templates/_search_box.html
{% load i18n %}
<form action="{% url 'search_results_list' %}" method="get">
    {{ form }}
    <button type="submit">{% trans "Search" %}</button>
</form>

app/templates/article_view.html
{% extends 'layout/base.html' %}

{% block content %}
    <h1>
        {{ article.name }}
        <small>{{ article.updated_at }}</small>
    </h1>
    <p>
        {{ article.content|safe }}
    </p>
    <div>
        <ul>
            <li>{{ article.upvotes }}</li>
            <li>{{ article.downvotes }}</li>
        </ul>
    </div>
{% endblock content %}

app/templates/category_view.html
{% extends 'layout/base.html' %}

{% block content %}
    <h1>
        {{ category.name }}
    </h1>
    <ul>
        {% for article in category.article_set.all %}
        <li>
            <a href="{% url 'ArticleDefaultView' article.slug %}">{{ article.name }}</a>
        </li>
    {% endfor %}
    </ul>

{% endblock content %}

app/templates/feedback_email.html
{% load i18n %}

{% trans "Hi" %},

{{ feedback_email }} {% trans "has said" %} <strong>{{ article.name }}</strong> {% trans "is not helfull, additionally they said" %}:

{{ feedback_message }}

{% trans "To view the article follow" %} <a href="{{ base_url }}{{ article.get_absolute_url }}">{% trans "this link" %}</a>.

app/templates/home.html
{% extends 'layout/base.html' %}
{% load i18n %}

{% block title %}{% trans "Home" %}{% endblock %}

{% block content %}
<section class="home">
    <div class="search-box-container">
        <h1>{% trans "How can we help you today?" %}</h1>
        {% include '_search_box.html' %}
    </div>
    <div class="container">
        <div class="categories-container">
            {% regroup object_list by category as category_list %}
            {% for category in category_list %}
                <div class="category">
                    <h2>
                        <a href="{{ category.grouper.get_absolute_url }}" class="title">
                            {{ category.grouper.name }}
                        </a>
                    </h2>
                    <ul>
                    {% for article in category.list|slice:":5" %}
                        <li>
                            <a href="{{ article.get_absolute_url }}">{{ article.name }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                    {% if category.list|length > 5 %}
                        <p><a class="btn gray view-all-btn" href="{{ category.grouper.get_absolute_url }}">{% trans "View All" %}</a></p>
                    {% endif %}
                </div>
            {% endfor %}
            {% if not category_list %}
                <div class="no-articles">
                    <h1>{% trans "There are no available articles" %}</h1>
                    <p>{% trans "Try again later" %}</p>
                </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

app/templates/login.html
{% extends 'layout/base.html' %}
{% load i18n %}

{% block title %}{% trans "Login" %}{% endblock %}

{% block content %}
<section class="login">
    <div class="breadcrumbs">
        <div class="container">
            <a href="{% url 'home' %}">{% trans "Home" %}</a> > {% trans "Login" %}
        </div>
    </div>
    <div class="container-xs info-container">
        <h1>{% trans "Login" %}</h1>

        <p>{% blocktrans %}Write your email address and we'll send you a link to log in{% endblocktrans %}.</p>

        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">{% trans "Send" %}</button>
        </form>
    </div>
</section>
{% endblock %}

app/templates/login_email.html
{% load i18n %}
<h1>{% trans "Login" %}</h1>
<p>{% blocktrans %}Please use this following link to log into the site{% endblocktrans %}:</p>
<p><a href="{{ url }}">{% trans "Click here to log in" %}</a></p>

app/templates/search_view.html
{% extends 'layout/base.html' %}

{% block content %}
    {% include '_search_box.html' %}

    {% for article in articles %}
        <h1>
            {{ article.name }}
        </h1>
        <p>
            {{ article.content }}
        </p>
        <a href="{% url 'ArticleDefaultView' article.slug %}">Leer más...</a>

    {% empty %}
    <p>No se encuentran resultados acordes con tu búsqueda, puedes abrir un nuevo tiquete con tu pregunta.</p>
    {% endfor %}
{% endblock %}